version: '3'
services:
  redis:
    image: 'redis:latest'
  solverjs:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4001:8081"
    volumes:
      - /home/node/solverjs/node_modules
      - ./:/home/node/solverjs
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379