FROM node:16-alpine
# RUN npm install -g nodemon

USER node

RUN mkdir -p /home/node/solverjs
WORKDIR /home/node/solverjs

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

CMD ["npm", "run", "dev"]